Added support for trailing slashes
LBPUnion/UnionPatcher pull request #32
Opened 2023-01-28 13:35 UTC by McMistrzYT

Trailing slahes (LITTLEBIGPLANETPS3_XML/) now get automatically removed instead of throwing an error.

2023-01-28 14:01 UTC, sudokoko approved these changes
LGTM, someone with authorization can merge this.

2023-01-29 06:11 UTC, Slendy requested changes
Thank you for your contribution to UnionPatcher. I have left you a few suggestions for how to optimize/better achieve your feature.

2023-01-29 06:11 UTC, Slendy commented on UnionPatcher/Patcher.cs
>          }
```suggestion
        if(serverUrl.EndsWith('/')) {
            throw new ArgumentException("URL must not contain a trailing slash!");
        }
```
If the URL sanitization is handled in the GUI code then this check should be fine

2023-02-09 19:02 UTC, sudokoko approved these changes
LGTM

2024-07-28 22:20 UTC, closed without merging